
begin;

create table if not exists public.thinktank_troubleshooting_sources (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.thinktank_troubleshooting_sessions(id) on delete cascade,
  source_type text not null check (source_type in ('zoom_transcript','caption_screenshot','text_transcript','other')),
  file_name text not null,
  mime_type text,
  storage_path text,
  extracted_text text not null default '',
  char_count integer not null default 0,
  status text not null default 'ready' check (status in ('processing','ready','failed')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists thinktank_troubleshooting_sources_session_idx
  on public.thinktank_troubleshooting_sources(session_id, created_at desc);

create table if not exists public.thinktank_troubleshooting_source_chunks (
  id bigint generated by default as identity primary key,
  source_id uuid not null references public.thinktank_troubleshooting_sources(id) on delete cascade,
  chunk_index integer not null,
  content text not null,
  created_at timestamptz not null default now(),
  unique(source_id, chunk_index)
);

create index if not exists thinktank_troubleshooting_source_chunks_source_idx
  on public.thinktank_troubleshooting_source_chunks(source_id, chunk_index);

alter table public.thinktank_troubleshooting_sources enable row level security;
alter table public.thinktank_troubleshooting_source_chunks enable row level security;

revoke all on table public.thinktank_troubleshooting_sources from anon, authenticated;
revoke all on table public.thinktank_troubleshooting_source_chunks from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'thinktank-troubleshooting-evidence',
  'thinktank-troubleshooting-evidence',
  false,
  10485760,
  array[
    'text/plain',
    'text/vtt',
    'application/x-subrip',
    'text/markdown',
    'text/csv',
    'application/json',
    'image/png',
    'image/jpeg',
    'image/webp'
  ]
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

commit;
