
begin;

create table if not exists public.thinktank_projects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text not null default '',
  category text,
  status text not null default 'active'
    check (status in ('planned','active','on_hold','completed','archived')),
  objective text,
  current_focus text,
  next_action text,
  due_date date,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists thinktank_projects_status_idx
  on public.thinktank_projects(status, updated_at desc);

create table if not exists public.thinktank_project_events (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.thinktank_projects(id) on delete cascade,
  sequence integer not null,
  event_type text not null
    check (event_type in ('note','update','decision','milestone','blocker','meeting','idea','reference')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(project_id, sequence)
);

create index if not exists thinktank_project_events_project_idx
  on public.thinktank_project_events(project_id, sequence);

create table if not exists public.thinktank_project_tasks (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.thinktank_projects(id) on delete cascade,
  title text not null,
  status text not null default 'todo'
    check (status in ('todo','doing','blocked','done','cancelled')),
  priority text not null default 'normal'
    check (priority in ('low','normal','high','urgent')),
  due_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists thinktank_project_tasks_project_idx
  on public.thinktank_project_tasks(project_id, status, due_date);

create table if not exists public.thinktank_project_sources (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.thinktank_projects(id) on delete cascade,
  source_type text not null
    check (source_type in ('zoom_transcript','caption_screenshot','text_transcript','document','other')),
  file_name text not null,
  mime_type text,
  storage_path text,
  extracted_text text not null default '',
  char_count integer not null default 0,
  status text not null default 'ready'
    check (status in ('processing','ready','failed')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists thinktank_project_sources_project_idx
  on public.thinktank_project_sources(project_id, created_at desc);

create table if not exists public.thinktank_project_source_chunks (
  id bigint generated by default as identity primary key,
  source_id uuid not null references public.thinktank_project_sources(id) on delete cascade,
  chunk_index integer not null,
  content text not null,
  created_at timestamptz not null default now(),
  unique(source_id, chunk_index)
);

create index if not exists thinktank_project_source_chunks_source_idx
  on public.thinktank_project_source_chunks(source_id, chunk_index);

alter table public.thinktank_projects enable row level security;
alter table public.thinktank_project_events enable row level security;
alter table public.thinktank_project_tasks enable row level security;
alter table public.thinktank_project_sources enable row level security;
alter table public.thinktank_project_source_chunks enable row level security;

revoke all on table public.thinktank_projects from anon, authenticated;
revoke all on table public.thinktank_project_events from anon, authenticated;
revoke all on table public.thinktank_project_tasks from anon, authenticated;
revoke all on table public.thinktank_project_sources from anon, authenticated;
revoke all on table public.thinktank_project_source_chunks from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'thinktank-project-evidence',
  'thinktank-project-evidence',
  false,
  10485760,
  array[
    'text/plain',
    'text/vtt',
    'application/x-subrip',
    'text/markdown',
    'text/csv',
    'application/json',
    'image/png',
    'image/jpeg',
    'image/webp'
  ]
)
on conflict (id) do update set
  public=false,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

commit;
