
begin;

create table if not exists public.thinktank_troubleshooting_sessions (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  symptom text not null,
  facility_key text,
  process_area text,
  systems text[] not null default '{}'::text[],
  status text not null default 'open'
    check (status in ('open','monitoring','resolved','closed')),
  current_hypothesis text,
  root_cause text,
  resolution text,
  resolution_summary text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists thinktank_troubleshooting_sessions_status_idx
  on public.thinktank_troubleshooting_sessions(status, started_at desc);

create table if not exists public.thinktank_troubleshooting_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.thinktank_troubleshooting_sessions(id) on delete cascade,
  sequence integer not null,
  actor text not null default 'Dylan'
    check (actor in ('Dylan','GPT','Claude','System','Ops','Vendor')),
  event_type text not null
    check (event_type in ('observation','question','analysis','hypothesis','test','result','action','evidence','decision','resolution','note')),
  content text not null,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(session_id, sequence)
);

create index if not exists thinktank_troubleshooting_events_session_idx
  on public.thinktank_troubleshooting_events(session_id, sequence);

alter table public.thinktank_troubleshooting_sessions enable row level security;
alter table public.thinktank_troubleshooting_events enable row level security;

revoke all on table public.thinktank_troubleshooting_sessions from anon, authenticated;
revoke all on table public.thinktank_troubleshooting_events from anon, authenticated;

commit;
