-- Persistent Think Tank agent task engine
create table if not exists public.thinktank_agent_tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  goal text not null,
  status text not null default 'queued'
    check (status in ('queued','running','waiting_approval','completed','failed','cancelled')),
  max_steps integer not null default 30 check (max_steps between 1 and 100),
  step_count integer not null default 0 check (step_count >= 0),
  working_state jsonb not null default '{}'::jsonb,
  pending_activity_id uuid references public.thinktank_tool_activity(id) on delete set null,
  last_model text not null default 'GPT' check (last_model in ('GPT','Claude','System')),
  result text,
  error_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create index if not exists thinktank_agent_tasks_status_updated_idx
  on public.thinktank_agent_tasks (status, updated_at desc);

create table if not exists public.thinktank_agent_steps (
  id bigint generated by default as identity primary key,
  task_id uuid not null references public.thinktank_agent_tasks(id) on delete cascade,
  sequence integer not null,
  actor text not null check (actor in ('GPT','Claude','System')),
  kind text not null check (kind in ('model','tool','checkpoint','system')),
  status text not null default 'succeeded'
    check (status in ('requested','waiting','succeeded','failed','denied')),
  summary text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (task_id, sequence)
);

create index if not exists thinktank_agent_steps_task_sequence_idx
  on public.thinktank_agent_steps (task_id, sequence desc);

alter table public.thinktank_agent_tasks enable row level security;
alter table public.thinktank_agent_steps enable row level security;

revoke all on table public.thinktank_agent_tasks from anon, authenticated;
revoke all on table public.thinktank_agent_steps from anon, authenticated;
