begin;

create table if not exists public.thinktank_knowledge_sources (
  document_id uuid primary key references public.thinktank_documents(id) on delete cascade,
  document_type text not null default 'general_reference'
    check (document_type in ('sop','system_doc','process_map','training','vendor_doc','general_reference')),
  authority text not null default 'general_reference'
    check (authority in ('official_sop','system_document','process_map','training','vendor_reference','general_reference')),
  scope jsonb not null default '{}'::jsonb,
  effective_date date,
  version_label text,
  status text not null default 'current'
    check (status in ('current','superseded','draft')),
  extraction_status text not null default 'pending'
    check (extraction_status in ('pending','processing','ready','error')),
  summary text,
  metadata jsonb not null default '{}'::jsonb,
  analyzed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.thinktank_process_nodes (
  id uuid primary key default gen_random_uuid(),
  canonical_key text not null unique,
  node_type text not null
    check (node_type in ('process','system','physical_action','decision','queue','resource','metric','exception')),
  name text not null,
  description text,
  parent_id uuid references public.thinktank_process_nodes(id) on delete set null,
  scope jsonb not null default '{}'::jsonb,
  aliases text[] not null default '{}'::text[],
  status text not null default 'active'
    check (status in ('active','retired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.thinktank_process_claims (
  id uuid primary key default gen_random_uuid(),
  claim_key text not null,
  subject_node_id uuid references public.thinktank_process_nodes(id) on delete set null,
  claim_type text not null
    check (claim_type in ('sequence','system_action','physical_action','rule','exception','input','output','dependency','capacity','metric','customization')),
  statement text not null,
  structured jsonb not null default '{}'::jsonb,
  scope jsonb not null default '{}'::jsonb,
  authority text not null
    check (authority in ('confirmed_operational','official_sop','system_document','process_map','training','vendor_reference','general_reference','observed','inferred')),
  confidence real not null default 0.7 check (confidence >= 0 and confidence <= 1),
  source_effective_date date,
  status text not null default 'active'
    check (status in ('active','proposed','superseded','disputed','retired')),
  supersedes_claim_id uuid references public.thinktank_process_claims(id) on delete set null,
  embedding vector(1536),
  fts tsvector generated always as (
    setweight(to_tsvector('simple', coalesce(claim_key,'')), 'A') ||
    setweight(to_tsvector('simple', coalesce(statement,'')), 'B')
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists thinktank_process_claims_one_active_key
  on public.thinktank_process_claims(claim_key)
  where status='active';

create index if not exists thinktank_process_claims_key_idx
  on public.thinktank_process_claims(claim_key,status);

create index if not exists thinktank_process_claims_fts_idx
  on public.thinktank_process_claims using gin(fts);

create index if not exists thinktank_process_claims_subject_idx
  on public.thinktank_process_claims(subject_node_id);

create table if not exists public.thinktank_process_evidence (
  id bigint generated by default as identity primary key,
  claim_id uuid not null references public.thinktank_process_claims(id) on delete cascade,
  source_type text not null
    check (source_type in ('document','conversation','manual','agent','observation')),
  document_id uuid references public.thinktank_documents(id) on delete set null,
  source_ref text,
  excerpt text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists thinktank_process_evidence_claim_idx
  on public.thinktank_process_evidence(claim_id);

create index if not exists thinktank_process_evidence_document_idx
  on public.thinktank_process_evidence(document_id);

create table if not exists public.thinktank_process_corrections (
  id uuid primary key default gen_random_uuid(),
  target_claim_id uuid references public.thinktank_process_claims(id) on delete set null,
  resulting_claim_id uuid references public.thinktank_process_claims(id) on delete set null,
  correction_text text not null,
  source_type text not null
    check (source_type in ('document','conversation','manual','agent','observation')),
  status text not null default 'proposed'
    check (status in ('proposed','applied','confirmed','rejected','conflict')),
  reason text,
  scope jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_by text not null default 'System'
    check (created_by in ('Dylan','GPT','Claude','System')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists thinktank_process_corrections_status_idx
  on public.thinktank_process_corrections(status,created_at desc);

create table if not exists public.thinktank_state_snapshots (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  captured_at timestamptz not null,
  source_type text not null
    check (source_type in ('screenshot','csv','excel','api','manual','json')),
  scope jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.thinktank_state_metrics (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null references public.thinktank_state_snapshots(id) on delete cascade,
  process_node_id uuid references public.thinktank_process_nodes(id) on delete set null,
  metric_key text not null,
  value_numeric numeric,
  value_text text,
  unit text,
  dimensions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists thinktank_state_metrics_snapshot_idx
  on public.thinktank_state_metrics(snapshot_id);

alter table public.thinktank_knowledge_sources enable row level security;
alter table public.thinktank_process_nodes enable row level security;
alter table public.thinktank_process_claims enable row level security;
alter table public.thinktank_process_evidence enable row level security;
alter table public.thinktank_process_corrections enable row level security;
alter table public.thinktank_state_snapshots enable row level security;
alter table public.thinktank_state_metrics enable row level security;

revoke all on table public.thinktank_knowledge_sources from anon, authenticated;
revoke all on table public.thinktank_process_nodes from anon, authenticated;
revoke all on table public.thinktank_process_claims from anon, authenticated;
revoke all on table public.thinktank_process_evidence from anon, authenticated;
revoke all on table public.thinktank_process_corrections from anon, authenticated;
revoke all on table public.thinktank_state_snapshots from anon, authenticated;
revoke all on table public.thinktank_state_metrics from anon, authenticated;

create or replace function public.match_thinktank_process_claims(
  query_embedding vector(1536),
  match_count integer default 12
)
returns table (
  id uuid,
  claim_key text,
  claim_type text,
  statement text,
  structured jsonb,
  scope jsonb,
  authority text,
  confidence real,
  source_effective_date date,
  similarity float
)
language sql
stable
set search_path=public
as $fn$
  select
    c.id,c.claim_key,c.claim_type,c.statement,c.structured,c.scope,
    c.authority,c.confidence,c.source_effective_date,
    (1 - (c.embedding <=> query_embedding))::float as similarity
  from public.thinktank_process_claims c
  where c.status='active' and c.embedding is not null
  order by c.embedding <=> query_embedding
  limit greatest(1, least(coalesce(match_count,12), 30));
$fn$;

create or replace function public.search_thinktank_process_claims(
  search_text text,
  match_count integer default 12
)
returns table (
  id uuid,
  claim_key text,
  claim_type text,
  statement text,
  structured jsonb,
  scope jsonb,
  authority text,
  confidence real,
  source_effective_date date,
  rank real
)
language sql
stable
set search_path=public
as $fn$
  select
    c.id,c.claim_key,c.claim_type,c.statement,c.structured,c.scope,
    c.authority,c.confidence,c.source_effective_date,
    ts_rank(c.fts, websearch_to_tsquery('simple', search_text))::real as rank
  from public.thinktank_process_claims c
  where c.status='active'
    and c.fts @@ websearch_to_tsquery('simple', search_text)
  order by rank desc
  limit greatest(1, least(coalesce(match_count,12), 30));
$fn$;

revoke all on function public.match_thinktank_process_claims(vector,integer) from public, anon, authenticated;
revoke all on function public.search_thinktank_process_claims(text,integer) from public, anon, authenticated;

commit;
